/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Data.DataAccessorFile;
import Logic.Controller;
import Logic.Member;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kasper Jeppesen
 */
public class Main extends javax.swing.JFrame
{
    private CardLayout card;
    
    private DefaultTableModel model; 
    private DataAccessorFile data = new DataAccessorFile();
    private Controller c = new Controller(data);

    /**
     * Creates new form Main
     */
    public Main()
    {
        initComponents();
        card = (CardLayout) mainPanel.getLayout();
        
        try
        {
            c.updateEverythingFromSource();
        }
        catch(NullPointerException npe)
        {
            System.out.println(npe);
            System.out.println("File \"Members.dat\" is empty");
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mainPanel = new javax.swing.JPanel();
        MainMenu = new javax.swing.JPanel();
        RegNewMember = new javax.swing.JButton();
        ManageMembers = new javax.swing.JButton();
        ManageTeams = new javax.swing.JButton();
        ViewTourParticipants = new javax.swing.JButton();
        ManageEconomy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RegisterNewMember = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        EmailAddress = new javax.swing.JLabel();
        EmailAddressTF = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        Phonenumber = new javax.swing.JLabel();
        DateOfBirth = new javax.swing.JLabel();
        ZipCode = new javax.swing.JLabel();
        AddressTF = new javax.swing.JTextField();
        ZipCodeTF = new javax.swing.JTextField();
        PhoneNumberTF = new javax.swing.JTextField();
        DateOfBirthTF = new javax.swing.JTextField();
        CityTF = new javax.swing.JTextField();
        ConfirmChanges = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        MainMenu1 = new javax.swing.JButton();
        SaveMembers = new javax.swing.JButton();
        ManageMember = new javax.swing.JPanel();
        ManMembers = new javax.swing.JLabel();
        MainMenu2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MembersTable = new javax.swing.JTable();
        RegisterNewMember1 = new javax.swing.JButton();
        CancelMembership = new javax.swing.JButton();
        MemberInfo = new javax.swing.JButton();
        MemberInformation = new javax.swing.JPanel();
        ChosenMemberName = new javax.swing.JLabel();
        MainMenu3 = new javax.swing.JButton();
        ActivityStatus = new javax.swing.JLabel();
        MemberID = new javax.swing.JLabel();
        DateOfJoing = new javax.swing.JLabel();
        MemberType = new javax.swing.JLabel();
        ActivityStatusTFMI = new javax.swing.JTextField();
        MemberIDTFMI = new javax.swing.JTextField();
        MemberTypeMI = new javax.swing.JTextField();
        DateOfJoiningTFMI = new javax.swing.JTextField();
        NextPaymentDate = new javax.swing.JLabel();
        ArrearsBalance = new javax.swing.JLabel();
        MembershipPrice = new javax.swing.JLabel();
        MembershipPriceTFMI = new javax.swing.JTextField();
        NextPaymentDateTFMI = new javax.swing.JTextField();
        ArrearsBalanceTFMI = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TournamentsParticipantsTable = new javax.swing.JTable();
        TournamentParticipants = new javax.swing.JLabel();
        TeamMembership = new javax.swing.JLabel();
        PhoneNumber1 = new javax.swing.JLabel();
        DateOfBirth1 = new javax.swing.JLabel();
        ZipCode1 = new javax.swing.JLabel();
        City1 = new javax.swing.JLabel();
        Address1 = new javax.swing.JLabel();
        EmailAddress1 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        PhoneNumberTFMI = new javax.swing.JTextField();
        DateOfBirthTFMI = new javax.swing.JTextField();
        ZipCodeTFMI = new javax.swing.JTextField();
        AddressTFMI = new javax.swing.JTextField();
        CityTFMI = new javax.swing.JTextField();
        NameTFMI = new javax.swing.JTextField();
        EmailAddressTFMI = new javax.swing.JTextField();
        TournamentEligibilityCB = new javax.swing.JCheckBox();
        Teams = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        BreaststrokeSeniorTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        CrawlSeniorTable = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        ButterflySeniorTable = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        BackCrawlSeniorTable = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        CrawlJuniorTable = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        ButterflyJuniorTable = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        BackCrawlJuniorTable = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        BreaststrokeJuniorTable = new javax.swing.JTable();
        JuniorTeams = new javax.swing.JLabel();
        SeniorTeams = new javax.swing.JLabel();
        Breaststroke = new javax.swing.JLabel();
        Breaststroke1 = new javax.swing.JLabel();
        Crawl = new javax.swing.JLabel();
        Crawl1 = new javax.swing.JLabel();
        BackCrawl = new javax.swing.JLabel();
        BackCrawl1 = new javax.swing.JLabel();
        Butterfly = new javax.swing.JLabel();
        Butterfly1 = new javax.swing.JLabel();
        MainMenu4 = new javax.swing.JButton();
        CreateTeam = new javax.swing.JButton();
        SpecificTeam = new javax.swing.JPanel();
        SpecificTeamTable = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        SpecificTeamName = new javax.swing.JLabel();
        TeamTrainer = new javax.swing.JLabel();
        TeamTrainerName = new javax.swing.JLabel();
        MainMenu5 = new javax.swing.JButton();
        AddNewTeamMember = new javax.swing.JButton();
        RemoveFromTeam = new javax.swing.JButton();
        CreateANewTeam = new javax.swing.JPanel();
        BreaststrokeCB = new javax.swing.JCheckBox();
        CrawlCB = new javax.swing.JCheckBox();
        BackCrawlCB = new javax.swing.JCheckBox();
        ButterflyCB = new javax.swing.JCheckBox();
        ChooseSwimmingstyle = new javax.swing.JLabel();
        ChooseJorS = new javax.swing.JLabel();
        JuniorCB = new javax.swing.JCheckBox();
        SeniorCB = new javax.swing.JCheckBox();
        TeamName = new javax.swing.JLabel();
        TeamNameTF = new javax.swing.JTextField();
        TrainerName = new javax.swing.JLabel();
        TrainerNameTF = new javax.swing.JTextField();
        ConfirmAndCreateTeam = new javax.swing.JButton();
        MainMenu6 = new javax.swing.JButton();

        jMenuItem1.setText("View / change selected member info");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cancel membership");
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("Register membership");
        jPopupMenu1.add(jMenuItem3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        RegNewMember.setText("Register new member");
        RegNewMember.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RegNewMemberActionPerformed(evt);
            }
        });

        ManageMembers.setText("Manage members");
        ManageMembers.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ManageMembersActionPerformed(evt);
            }
        });

        ManageTeams.setText("Manage Teams");
        ManageTeams.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ManageTeamsActionPerformed(evt);
            }
        });

        ViewTourParticipants.setText("View tournament participants");
        ViewTourParticipants.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ViewTourParticipantsActionPerformed(evt);
            }
        });

        ManageEconomy.setText("Manage economy");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Delfinen Svømmeklub");

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegNewMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageTeams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewTourParticipants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageEconomy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(RegNewMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageMembers)
                .addGap(78, 78, 78)
                .addComponent(ManageTeams)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewTourParticipants)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(ManageEconomy)
                .addGap(82, 82, 82))
        );

        mainPanel.add(MainMenu, "card2");

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setText("Name:");

        EmailAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmailAddress.setText("Email address: ");

        Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Address.setText("Address:");

        City.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        City.setText("City:");

        Phonenumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Phonenumber.setText("Phone number:");

        DateOfBirth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateOfBirth.setText("Date of birth:");

        ZipCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ZipCode.setText("Zip code:");

        ConfirmChanges.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ConfirmChanges.setText("Confirm changes");
        ConfirmChanges.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConfirmChangesActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ResetActionPerformed(evt);
            }
        });

        MainMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MainMenu1.setText("Main menu");
        MainMenu1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MainMenu1ActionPerformed(evt);
            }
        });

        SaveMembers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SaveMembers.setText("Save members");

        javax.swing.GroupLayout RegisterNewMemberLayout = new javax.swing.GroupLayout(RegisterNewMember);
        RegisterNewMember.setLayout(RegisterNewMemberLayout);
        RegisterNewMemberLayout.setHorizontalGroup(
            RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                        .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterNewMemberLayout.createSequentialGroup()
                                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                                                    .addComponent(DateOfBirth)
                                                    .addGap(27, 27, 27))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterNewMemberLayout.createSequentialGroup()
                                                    .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Reset)
                                                        .addComponent(Phonenumber))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                            .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                                                .addComponent(ZipCode)
                                                .addGap(56, 56, 56)))
                                        .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                                            .addComponent(City)
                                            .addGap(87, 87, 87)))
                                    .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                                        .addComponent(Address)
                                        .addGap(58, 58, 58)))
                                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddressTF, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(CityTF)
                                    .addComponent(ZipCodeTF)
                                    .addComponent(DateOfBirthTF)
                                    .addComponent(PhoneNumberTF)
                                    .addComponent(ConfirmChanges)))
                            .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailAddress)
                                    .addComponent(Name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(EmailAddressTF))))
                        .addGap(0, 203, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterNewMemberLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MainMenu1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterNewMemberLayout.createSequentialGroup()
                                .addComponent(SaveMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))))
        );
        RegisterNewMemberLayout.setVerticalGroup(
            RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterNewMemberLayout.createSequentialGroup()
                .addComponent(MainMenu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailAddress)
                    .addComponent(EmailAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address)
                    .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(City)
                    .addComponent(CityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZipCode)
                    .addComponent(ZipCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateOfBirthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateOfBirth))
                .addGap(18, 18, 18)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phonenumber))
                .addGap(61, 61, 61)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmChanges)
                    .addComponent(Reset))
                .addGap(35, 35, 35)
                .addComponent(SaveMembers)
                .addGap(25, 25, 25))
        );

        mainPanel.add(RegisterNewMember, "RegiNewMember");

        ManMembers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ManMembers.setText("Manage members");

        MainMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MainMenu2.setText("Main Menu");
        MainMenu2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MainMenu2ActionPerformed(evt);
            }
        });

        MembersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Name", "MID", "Status"
            }
        ));
        MembersTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                MembersTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(MembersTable);

        RegisterNewMember1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegisterNewMember1.setText("Register new member");
        RegisterNewMember1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RegisterNewMember1ActionPerformed(evt);
            }
        });

        CancelMembership.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelMembership.setText("Cancel membership");

        MemberInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MemberInfo.setText("View / chance member info");
        MemberInfo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MemberInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageMemberLayout = new javax.swing.GroupLayout(ManageMember);
        ManageMember.setLayout(ManageMemberLayout);
        ManageMemberLayout.setHorizontalGroup(
            ManageMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageMemberLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(ManMembers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(MainMenu2))
            .addGroup(ManageMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(MemberInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageMemberLayout.createSequentialGroup()
                        .addComponent(RegisterNewMember1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelMembership)))
                .addContainerGap())
        );
        ManageMemberLayout.setVerticalGroup(
            ManageMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageMemberLayout.createSequentialGroup()
                .addGroup(ManageMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManMembers)
                    .addComponent(MainMenu2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManageMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageMemberLayout.createSequentialGroup()
                        .addComponent(CancelMembership)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageMemberLayout.createSequentialGroup()
                        .addComponent(RegisterNewMember1)
                        .addGap(9, 9, 9)))
                .addComponent(MemberInfo)
                .addGap(26, 26, 26))
        );

        mainPanel.add(ManageMember, "MembersManage");

        ChosenMemberName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ChosenMemberName.setText("-----------------");

        MainMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MainMenu3.setText("Main menu");
        MainMenu3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MainMenu3ActionPerformed(evt);
            }
        });

        ActivityStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ActivityStatus.setText("Activity status:");

        MemberID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MemberID.setText("Member ID:");

        DateOfJoing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateOfJoing.setText("Date of joining:");

        MemberType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MemberType.setText("Member type:");

        ActivityStatusTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        MemberIDTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        MemberTypeMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        DateOfJoiningTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NextPaymentDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NextPaymentDate.setText("Next payment date:");

        ArrearsBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ArrearsBalance.setText("Arrears balance:");

        MembershipPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MembershipPrice.setText("Membership price:");

        MembershipPriceTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NextPaymentDateTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ArrearsBalanceTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Team name", "Swimming style", "Date of joining", "Date of leaving"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        TournamentsParticipantsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String []
            {
                "Eent name", "Event date", "Ranking", "Swimming style", "Time"
            }
        ));
        jScrollPane4.setViewportView(TournamentsParticipantsTable);

        TournamentParticipants.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TournamentParticipants.setText("Tournaments participants");

        TeamMembership.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TeamMembership.setText("Team membership");

        PhoneNumber1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PhoneNumber1.setText("Phone number:");

        DateOfBirth1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateOfBirth1.setText("Date of birth:");

        ZipCode1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ZipCode1.setText("Zip code:");

        City1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        City1.setText("City::");

        Address1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Address1.setText("Address:");

        EmailAddress1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmailAddress1.setText("Email Address:");

        Name1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name1.setText("Name:");

        PhoneNumberTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        DateOfBirthTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ZipCodeTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        AddressTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        CityTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NameTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        EmailAddressTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TournamentEligibilityCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TournamentEligibilityCB.setText("Tournament eligibility");

        javax.swing.GroupLayout MemberInformationLayout = new javax.swing.GroupLayout(MemberInformation);
        MemberInformation.setLayout(MemberInformationLayout);
        MemberInformationLayout.setHorizontalGroup(
            MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberInformationLayout.createSequentialGroup()
                .addComponent(ChosenMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(MainMenu3))
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MemberInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MemberInformationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TournamentEligibilityCB))
                    .addGroup(MemberInformationLayout.createSequentialGroup()
                        .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MemberInformationLayout.createSequentialGroup()
                                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NextPaymentDate)
                                    .addComponent(ArrearsBalance))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NextPaymentDateTFMI, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(ArrearsBalanceTFMI))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateOfBirth1)
                                    .addComponent(PhoneNumber1)))
                            .addGroup(MemberInformationLayout.createSequentialGroup()
                                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MemberInformationLayout.createSequentialGroup()
                                        .addComponent(DateOfJoing)
                                        .addGap(18, 18, 18)
                                        .addComponent(DateOfJoiningTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(MemberInformationLayout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addComponent(MemberIDTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5)
                                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ZipCode1)
                                    .addComponent(Address1)
                                    .addComponent(EmailAddress1)
                                    .addComponent(City1)))
                            .addGroup(MemberInformationLayout.createSequentialGroup()
                                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ActivityStatus)
                                    .addComponent(MemberID)
                                    .addComponent(MemberType))
                                .addGap(21, 21, 21)
                                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ActivityStatusTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MemberTypeMI, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Name1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNumberTFMI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DateOfBirthTFMI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ZipCodeTFMI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CityTFMI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddressTFMI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EmailAddressTFMI)
                            .addComponent(NameTFMI, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(41, 41, 41))
            .addGroup(MemberInformationLayout.createSequentialGroup()
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemberInformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MembershipPrice)
                        .addGap(18, 18, 18)
                        .addComponent(MembershipPriceTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MemberInformationLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(TeamMembership))
                    .addGroup(MemberInformationLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(TournamentParticipants)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MemberInformationLayout.setVerticalGroup(
            MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberInformationLayout.createSequentialGroup()
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChosenMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActivityStatus)
                    .addComponent(ActivityStatusTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name1)
                    .addComponent(NameTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MemberID)
                    .addComponent(MemberIDTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailAddress1)
                    .addComponent(EmailAddressTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MemberType)
                    .addComponent(MemberTypeMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address1)
                    .addComponent(AddressTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateOfJoing)
                    .addComponent(DateOfJoiningTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(City1)
                    .addComponent(CityTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZipCode1)
                    .addComponent(ZipCodeTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArrearsBalance)
                    .addComponent(ArrearsBalanceTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateOfBirth1)
                    .addComponent(DateOfBirthTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextPaymentDate)
                    .addComponent(NextPaymentDateTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber1)
                    .addComponent(PhoneNumberTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MembershipPrice)
                    .addComponent(MembershipPriceTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TournamentEligibilityCB)
                .addGap(5, 5, 5)
                .addComponent(TeamMembership)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TournamentParticipants)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(MemberInformation, "MemberInformation");

        BreaststrokeSeniorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Teams"
            }
        ));
        jScrollPane5.setViewportView(BreaststrokeSeniorTable);

        CrawlSeniorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Teams"
            }
        ));
        jScrollPane6.setViewportView(CrawlSeniorTable);

        ButterflySeniorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Teams"
            }
        ));
        jScrollPane7.setViewportView(ButterflySeniorTable);

        BackCrawlSeniorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Teams"
            }
        ));
        jScrollPane8.setViewportView(BackCrawlSeniorTable);

        CrawlJuniorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Teams"
            }
        ));
        jScrollPane9.setViewportView(CrawlJuniorTable);

        ButterflyJuniorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Teams"
            }
        ));
        jScrollPane10.setViewportView(ButterflyJuniorTable);

        BackCrawlJuniorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Teams"
            }
        ));
        jScrollPane11.setViewportView(BackCrawlJuniorTable);

        BreaststrokeJuniorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Teams"
            }
        ));
        jScrollPane12.setViewportView(BreaststrokeJuniorTable);

        JuniorTeams.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JuniorTeams.setText("Junior teams:");

        SeniorTeams.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        SeniorTeams.setText("Senior teams:");

        Breaststroke.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Breaststroke.setText("Breasstroke:");

        Breaststroke1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Breaststroke1.setText("Breasstroke:");

        Crawl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Crawl.setText("Crawl:");

        Crawl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Crawl1.setText("Crawl:");

        BackCrawl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackCrawl.setText("Back crawl:");

        BackCrawl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackCrawl1.setText("Back crawl:");

        Butterfly.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Butterfly.setText("Butterfly");

        Butterfly1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Butterfly1.setText("Butterfly");

        MainMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MainMenu4.setText("Main menu");
        MainMenu4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MainMenu4ActionPerformed(evt);
            }
        });

        CreateTeam.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CreateTeam.setText("Create a new Team");
        CreateTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CreateTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeamsLayout = new javax.swing.GroupLayout(Teams);
        Teams.setLayout(TeamsLayout);
        TeamsLayout.setHorizontalGroup(
            TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamsLayout.createSequentialGroup()
                .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TeamsLayout.createSequentialGroup()
                        .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TeamsLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Breaststroke))
                            .addGroup(TeamsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Breaststroke1)))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TeamsLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeamsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TeamsLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(Crawl1)
                                .addGap(70, 70, 70)
                                .addComponent(BackCrawl1)
                                .addGap(61, 61, 61)
                                .addComponent(Butterfly1))
                            .addGroup(TeamsLayout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TeamsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(SeniorTeams))
                            .addGroup(TeamsLayout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(TeamsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Crawl)
                        .addGap(88, 88, 88)
                        .addComponent(BackCrawl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Butterfly)
                        .addGap(41, 41, 41))))
            .addGroup(TeamsLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(JuniorTeams)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainMenu4))
            .addGroup(TeamsLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(CreateTeam)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TeamsLayout.setVerticalGroup(
            TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeamsLayout.createSequentialGroup()
                .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TeamsLayout.createSequentialGroup()
                        .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JuniorTeams)
                            .addComponent(MainMenu4))
                        .addGap(10, 10, 10)
                        .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Crawl)
                            .addComponent(BackCrawl)
                            .addComponent(Butterfly))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TeamsLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Breaststroke)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19)
                .addComponent(SeniorTeams)
                .addGap(3, 3, 3)
                .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Breaststroke1)
                    .addComponent(Crawl1)
                    .addComponent(BackCrawl1)
                    .addComponent(Butterfly1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(CreateTeam))
        );

        mainPanel.add(Teams, "Teams");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Name", "MID", "Best time", "Date of best score"
            }
        ));
        SpecificTeamTable.setViewportView(jTable3);

        SpecificTeamName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SpecificTeamName.setText("----------------------------");

        TeamTrainer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TeamTrainer.setText("Team trainer:");

        TeamTrainerName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TeamTrainerName.setText("--------------------------");

        MainMenu5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MainMenu5.setText("Main menu");
        MainMenu5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MainMenu5ActionPerformed(evt);
            }
        });

        AddNewTeamMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddNewTeamMember.setText("Add new team member");

        RemoveFromTeam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RemoveFromTeam.setText("Remove from team");

        javax.swing.GroupLayout SpecificTeamLayout = new javax.swing.GroupLayout(SpecificTeam);
        SpecificTeam.setLayout(SpecificTeamLayout);
        SpecificTeamLayout.setHorizontalGroup(
            SpecificTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SpecificTeamTable)
            .addGroup(SpecificTeamLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(SpecificTeamName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(MainMenu5))
            .addGroup(SpecificTeamLayout.createSequentialGroup()
                .addGroup(SpecificTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SpecificTeamLayout.createSequentialGroup()
                        .addComponent(TeamTrainer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TeamTrainerName))
                    .addGroup(SpecificTeamLayout.createSequentialGroup()
                        .addComponent(AddNewTeamMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoveFromTeam)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SpecificTeamLayout.setVerticalGroup(
            SpecificTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecificTeamLayout.createSequentialGroup()
                .addGroup(SpecificTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpecificTeamName)
                    .addComponent(MainMenu5))
                .addGap(29, 29, 29)
                .addGroup(SpecificTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeamTrainer)
                    .addComponent(TeamTrainerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpecificTeamTable, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(SpecificTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewTeamMember)
                    .addComponent(RemoveFromTeam)))
        );

        mainPanel.add(SpecificTeam, "SpecificTeam");

        BreaststrokeCB.setText("Breaststroke");

        CrawlCB.setText("Crawl");

        BackCrawlCB.setText("Back Crawl");

        ButterflyCB.setText("Buttlerfly");

        ChooseSwimmingstyle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ChooseSwimmingstyle.setText("Choose a swimming style:");

        ChooseJorS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ChooseJorS.setText("Choose junior or senior:");

        JuniorCB.setText("Junior");

        SeniorCB.setText("Senior");

        TeamName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TeamName.setText("Team name:");

        TrainerName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TrainerName.setText("Trainer name:");

        ConfirmAndCreateTeam.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ConfirmAndCreateTeam.setText("Comfirn and create team");

        MainMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MainMenu6.setText("Main menu");
        MainMenu6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MainMenu6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateANewTeamLayout = new javax.swing.GroupLayout(CreateANewTeam);
        CreateANewTeam.setLayout(CreateANewTeamLayout);
        CreateANewTeamLayout.setHorizontalGroup(
            CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateANewTeamLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmAndCreateTeam)
                    .addComponent(ButterflyCB)
                    .addComponent(BackCrawlCB)
                    .addGroup(CreateANewTeamLayout.createSequentialGroup()
                        .addGroup(CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChooseSwimmingstyle)
                            .addComponent(BreaststrokeCB)
                            .addComponent(CrawlCB))
                        .addGap(49, 49, 49)
                        .addGroup(CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeniorCB)
                            .addComponent(JuniorCB)
                            .addComponent(ChooseJorS)))
                    .addGroup(CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CreateANewTeamLayout.createSequentialGroup()
                            .addComponent(TrainerName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TrainerNameTF))
                        .addGroup(CreateANewTeamLayout.createSequentialGroup()
                            .addComponent(TeamName)
                            .addGap(18, 18, 18)
                            .addComponent(TeamNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateANewTeamLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainMenu6))
        );
        CreateANewTeamLayout.setVerticalGroup(
            CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateANewTeamLayout.createSequentialGroup()
                .addComponent(MainMenu6)
                .addGap(41, 41, 41)
                .addGroup(CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChooseSwimmingstyle)
                    .addComponent(ChooseJorS))
                .addGap(26, 26, 26)
                .addGroup(CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BreaststrokeCB)
                    .addComponent(JuniorCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrawlCB)
                    .addComponent(SeniorCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackCrawlCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButterflyCB)
                .addGap(51, 51, 51)
                .addGroup(CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeamName)
                    .addComponent(TeamNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(CreateANewTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TrainerName)
                    .addComponent(TrainerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(ConfirmAndCreateTeam)
                .addGap(54, 54, 54))
        );

        mainPanel.add(CreateANewTeam, "CreateATeam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageMembersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ManageMembersActionPerformed
    {//GEN-HEADEREND:event_ManageMembersActionPerformed
        //addRowToTable();
        card.show(mainPanel, "MembersManage");
    }//GEN-LAST:event_ManageMembersActionPerformed

    private void ConfirmChangesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConfirmChangesActionPerformed
    {//GEN-HEADEREND:event_ConfirmChangesActionPerformed
        try
        {
            // should be removed from this method at some point in time
            c.updateMemberList();
        }
        catch (Exception ex)
        {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int zipCode = Integer.parseInt(this.ZipCodeTF.getText());
        long phoneNumber = Long.parseLong(this.PhoneNumberTF.getText());
        String name = this.NameTF.getText();
        String address = this.AddressTF.getText();
        String city = this.CityTF.getText();
        String email = this.EmailAddressTF.getText();
        //LocalDate dateOfBirth = LocalDate.parse(this.DateOfBirthTF.getText()); //works if string is formatted like localdate (ex 2016-08-16)
        
        String dateOfBirthString = this.DateOfBirthTF.getText();
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("d/MM/yyyy");
        
        LocalDate dateOfBirth = LocalDate.parse(dateOfBirthString, dateFormat);
        
        validation();
        
        c.registerNewMember(zipCode, phoneNumber, name, address, city, email, dateOfBirth);
        System.out.print("MemberList size: " + c.getMemberList().size());
        
        try
        {
            // should be removed from this methid at some point in time
            c.saveMemberList();
        }
        catch (Exception ex)
        {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Object rowData[] = new Object[3];
                    
        rowData[0] = c.getLastAddedMember().getName();
        rowData[1] = c.getLastAddedMember().getMemberID();
        rowData[2] = c.getLastAddedMember().getActivityStatusString();
        model.addRow(rowData);
        reset();
    }//GEN-LAST:event_ConfirmChangesActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ResetActionPerformed
    {//GEN-HEADEREND:event_ResetActionPerformed
        reset();
    }//GEN-LAST:event_ResetActionPerformed

    private void MembersTableMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_MembersTableMouseReleased
    {//GEN-HEADEREND:event_MembersTableMouseReleased
         //Mouse Released is apperantly equal to mouse right click???? 
        if(evt.isPopupTrigger()) //If this event is triggrede (java.awt.event.Mouse event evt) - the parameter for this method
        {
            jPopupMenu1.show(this, evt.getX(), evt.getY()); //show the popup at memberstable at this event x,y cordinates
        }
    }//GEN-LAST:event_MembersTableMouseReleased

    private void MainMenu1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MainMenu1ActionPerformed
    {//GEN-HEADEREND:event_MainMenu1ActionPerformed
        mainMenu();
    }//GEN-LAST:event_MainMenu1ActionPerformed

    private void MainMenu2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MainMenu2ActionPerformed
    {//GEN-HEADEREND:event_MainMenu2ActionPerformed
        mainMenu();
    }//GEN-LAST:event_MainMenu2ActionPerformed

    private void RegisterNewMember1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegisterNewMember1ActionPerformed
    {//GEN-HEADEREND:event_RegisterNewMember1ActionPerformed
        card.show(mainPanel, "RegiNewMember");
    }//GEN-LAST:event_RegisterNewMember1ActionPerformed

    private void ViewTourParticipantsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ViewTourParticipantsActionPerformed
    {//GEN-HEADEREND:event_ViewTourParticipantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewTourParticipantsActionPerformed

    private void RegNewMemberActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegNewMemberActionPerformed
    {//GEN-HEADEREND:event_RegNewMemberActionPerformed
        card.show(mainPanel, "RegiNewMember");
    }//GEN-LAST:event_RegNewMemberActionPerformed

    private void MemberInfoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MemberInfoActionPerformed
    {//GEN-HEADEREND:event_MemberInfoActionPerformed
        memberInfo();
        card.show(mainPanel, "MemberInformation");
    }//GEN-LAST:event_MemberInfoActionPerformed

    private void MainMenu4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MainMenu4ActionPerformed
    {//GEN-HEADEREND:event_MainMenu4ActionPerformed
        mainMenu();
    }//GEN-LAST:event_MainMenu4ActionPerformed

    private void MainMenu3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MainMenu3ActionPerformed
    {//GEN-HEADEREND:event_MainMenu3ActionPerformed
        mainMenu();
    }//GEN-LAST:event_MainMenu3ActionPerformed

    private void ManageTeamsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ManageTeamsActionPerformed
    {//GEN-HEADEREND:event_ManageTeamsActionPerformed
        card.show(mainPanel, "Teams");
    }//GEN-LAST:event_ManageTeamsActionPerformed

    private void MainMenu5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MainMenu5ActionPerformed
    {//GEN-HEADEREND:event_MainMenu5ActionPerformed
        mainMenu();
    }//GEN-LAST:event_MainMenu5ActionPerformed

    private void CreateTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CreateTeamActionPerformed
    {//GEN-HEADEREND:event_CreateTeamActionPerformed
        card.show(mainPanel, "CreateATeam");
    }//GEN-LAST:event_CreateTeamActionPerformed

    private void MainMenu6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MainMenu6ActionPerformed
    {//GEN-HEADEREND:event_MainMenu6ActionPerformed
        mainMenu();
    }//GEN-LAST:event_MainMenu6ActionPerformed

    public void validation()
    {
        int zipCode = Integer.parseInt(this.ZipCodeTF.getText());
        long phoneNumber = Long.parseLong(this.PhoneNumberTF.getText());
        
        if(zipCode < 1000 || zipCode > 9999)
        {
            JOptionPane.showMessageDialog(null, "The field zip must contains excalty 4 digits", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        if(phoneNumber < 10000000 || phoneNumber > 99999999)
        {
            JOptionPane.showMessageDialog(null, "The field phone number must contains excalty 8 digits", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        if(this.NameTF.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "The field name cannot be empty", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        if(this.AddressTF.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "The field address cannot be empty", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        if(this.CityTF.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "The field city cannot be empty", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        
//        if(validateEmail(this.EmailAddressTF.getText()) == false)
//        {
//            JOptionPane.showMessageDialog(null, "This email address is not a valid email address", "Inane error", JOptionPane.ERROR_MESSAGE);
//        }
//        if(validateDate(this.DateOfBirthTF.getText()) == false)
//        {
//            JOptionPane.showMessageDialog(null, "This date is not a valid date", "Inane error", JOptionPane.ERROR_MESSAGE);
//        }
    }
    
    public void reset()
    {
        this.ZipCodeTF.setText("");
        this.PhoneNumberTF.setText("");
        this.NameTF.setText("");
        this.AddressTF.setText("");
        this.CityTF.setText("");
        this.EmailAddressTF.setText("");
        this.DateOfBirthTF.setText("");
    }
    
    public void populateTable()
    {
        model = (DefaultTableModel) MembersTable.getModel();
        System.out.print("MemberList size is: " + c.getMemberList().size());
        
        Object rowData[] = new Object[3];
        
        for(int i = 0; i < c.getMemberList().size(); ++i)
        {
            
            rowData[0] = c.getMemberList().get(i).getName();
            rowData[1] = c.getMemberList().get(i).getMemberID();
            rowData[2] = c.getMemberList().get(i).getActivityStatusString();
            model.addRow(rowData);
            
        }  
    }
    
    public void populateSpecificTeamTable()
    {
//        model = (DefaultTableModel) MembersTable.getModel();
//        //System.out.print("MemberList size is: " + c.//getTeamMemberList().size());
//        
//        Object rowData[] = new Object[4];
//        
//        //for(int i = 0; i < c.//getTeamMemberList.size(); ++i)
//        {
//            rowData[0] = c.//getTeamMemberList().get(i).getName(); 
//            rowData[1] = c.//getTeamMemberList().get(i).getMID();
//            rowData[2] = c.//getTeamMemberList().get(i).getDateOfJoining();
//            rowData[3] = c.//getTeamMemberList().get(i).getBestDateOfScore();
//            model.addRow(rowData);
//        }
    }
    
    public int rowSelected()
    {
        int index;
        
        if(MembersTable.getSelectionModel().isSelectionEmpty())
        {
            System.out.print("No rows selected");
        }
        
        index = MembersTable.getSelectedRow();
        return index;    
    }
    
    public void mainMenu()
    {
        card.first(mainPanel);
    }
    
    public void memberInfo()
    {
        int i = rowSelected();
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d/MM/yyyy");
        
        this.NameTFMI.setText(c.getMemberList().get(i).getName());
        this.EmailAddressTFMI.setText(c.getMemberList().get(i).getEmailAddress());
        this.AddressTFMI.setText(c.getMemberList().get(i).getAddress());
        this.CityTFMI.setText(c.getMemberList().get(i).getCity());
        this.ZipCodeTFMI.setText(Integer.toString(c.getMemberList().get(i).getZipCode()));
        this.DateOfBirthTFMI.setText(c.getMemberList().get(i).getDateOfBirth().format(formatter));
        this.PhoneNumberTFMI.setText(Long.toString(c.getMemberList().get(i).getPhoneNumber()));
        
        this.ActivityStatusTFMI.setText(c.getMemberList().get(i).getActivityStatusString());
        this.MemberIDTFMI.setText(Integer.toString(c.getMemberList().get(i).getMemberID()));
        this.MemberTypeMI.setText(c.getMemberList().get(i).getCompetitiveSwimmerString());
        this.DateOfJoiningTFMI.setText(c.getMemberList().get(i).getDateOfJoining().format(formatter));
        
        this.ArrearsBalanceTFMI.setText(Long.toString(c.getMemberList().get(i).getArrearsBalance()));
        this.NextPaymentDateTFMI.setText(c.getMemberList().get(i).getNextPaymentDate().format(formatter));
        this.MembershipPriceTFMI.setText(c.getMemberList().get(i).getMembershipPriceString());
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActivityStatus;
    private javax.swing.JTextField ActivityStatusTFMI;
    private javax.swing.JButton AddNewTeamMember;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address1;
    private javax.swing.JTextField AddressTF;
    private javax.swing.JTextField AddressTFMI;
    private javax.swing.JLabel ArrearsBalance;
    private javax.swing.JTextField ArrearsBalanceTFMI;
    private javax.swing.JLabel BackCrawl;
    private javax.swing.JLabel BackCrawl1;
    private javax.swing.JCheckBox BackCrawlCB;
    private javax.swing.JTable BackCrawlJuniorTable;
    private javax.swing.JTable BackCrawlSeniorTable;
    private javax.swing.JLabel Breaststroke;
    private javax.swing.JLabel Breaststroke1;
    private javax.swing.JCheckBox BreaststrokeCB;
    private javax.swing.JTable BreaststrokeJuniorTable;
    private javax.swing.JTable BreaststrokeSeniorTable;
    private javax.swing.JLabel Butterfly;
    private javax.swing.JLabel Butterfly1;
    private javax.swing.JCheckBox ButterflyCB;
    private javax.swing.JTable ButterflyJuniorTable;
    private javax.swing.JTable ButterflySeniorTable;
    private javax.swing.JButton CancelMembership;
    private javax.swing.JLabel ChooseJorS;
    private javax.swing.JLabel ChooseSwimmingstyle;
    private javax.swing.JLabel ChosenMemberName;
    private javax.swing.JLabel City;
    private javax.swing.JLabel City1;
    private javax.swing.JTextField CityTF;
    private javax.swing.JTextField CityTFMI;
    private javax.swing.JButton ConfirmAndCreateTeam;
    private javax.swing.JButton ConfirmChanges;
    private javax.swing.JLabel Crawl;
    private javax.swing.JLabel Crawl1;
    private javax.swing.JCheckBox CrawlCB;
    private javax.swing.JTable CrawlJuniorTable;
    private javax.swing.JTable CrawlSeniorTable;
    private javax.swing.JPanel CreateANewTeam;
    private javax.swing.JButton CreateTeam;
    private javax.swing.JLabel DateOfBirth;
    private javax.swing.JLabel DateOfBirth1;
    private javax.swing.JTextField DateOfBirthTF;
    private javax.swing.JTextField DateOfBirthTFMI;
    private javax.swing.JLabel DateOfJoing;
    private javax.swing.JTextField DateOfJoiningTFMI;
    private javax.swing.JLabel EmailAddress;
    private javax.swing.JLabel EmailAddress1;
    private javax.swing.JTextField EmailAddressTF;
    private javax.swing.JTextField EmailAddressTFMI;
    private javax.swing.JCheckBox JuniorCB;
    private javax.swing.JLabel JuniorTeams;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton MainMenu1;
    private javax.swing.JButton MainMenu2;
    private javax.swing.JButton MainMenu3;
    private javax.swing.JButton MainMenu4;
    private javax.swing.JButton MainMenu5;
    private javax.swing.JButton MainMenu6;
    private javax.swing.JLabel ManMembers;
    private javax.swing.JButton ManageEconomy;
    private javax.swing.JPanel ManageMember;
    private javax.swing.JButton ManageMembers;
    private javax.swing.JButton ManageTeams;
    private javax.swing.JLabel MemberID;
    private javax.swing.JTextField MemberIDTFMI;
    private javax.swing.JButton MemberInfo;
    private javax.swing.JPanel MemberInformation;
    private javax.swing.JLabel MemberType;
    private javax.swing.JTextField MemberTypeMI;
    private javax.swing.JTable MembersTable;
    private javax.swing.JLabel MembershipPrice;
    private javax.swing.JTextField MembershipPriceTFMI;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JTextField NameTF;
    private javax.swing.JTextField NameTFMI;
    private javax.swing.JLabel NextPaymentDate;
    private javax.swing.JTextField NextPaymentDateTFMI;
    private javax.swing.JLabel PhoneNumber1;
    private javax.swing.JTextField PhoneNumberTF;
    private javax.swing.JTextField PhoneNumberTFMI;
    private javax.swing.JLabel Phonenumber;
    private javax.swing.JButton RegNewMember;
    private javax.swing.JPanel RegisterNewMember;
    private javax.swing.JButton RegisterNewMember1;
    private javax.swing.JButton RemoveFromTeam;
    private javax.swing.JButton Reset;
    private javax.swing.JButton SaveMembers;
    private javax.swing.JCheckBox SeniorCB;
    private javax.swing.JLabel SeniorTeams;
    private javax.swing.JPanel SpecificTeam;
    private javax.swing.JLabel SpecificTeamName;
    private javax.swing.JScrollPane SpecificTeamTable;
    private javax.swing.JLabel TeamMembership;
    private javax.swing.JLabel TeamName;
    private javax.swing.JTextField TeamNameTF;
    private javax.swing.JLabel TeamTrainer;
    private javax.swing.JLabel TeamTrainerName;
    private javax.swing.JPanel Teams;
    private javax.swing.JCheckBox TournamentEligibilityCB;
    private javax.swing.JLabel TournamentParticipants;
    private javax.swing.JTable TournamentsParticipantsTable;
    private javax.swing.JLabel TrainerName;
    private javax.swing.JTextField TrainerNameTF;
    private javax.swing.JButton ViewTourParticipants;
    private javax.swing.JLabel ZipCode;
    private javax.swing.JLabel ZipCode1;
    private javax.swing.JTextField ZipCodeTF;
    private javax.swing.JTextField ZipCodeTFMI;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
