/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Data.DataAccessorFile;
import Logic.Controller;
import Logic.Member;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kasper Jeppesen
 */
public class Main extends javax.swing.JFrame
{
    private CardLayout card;
    
    private DefaultTableModel model; 
    private DataAccessorFile data = new DataAccessorFile();
    private Controller c = new Controller(data);

    /**
     * Creates new form Main
     */
    public Main()
    {
        initComponents();
        card = (CardLayout) mainPanel.getLayout();
        
        try
        {
            c.updateMemberList();
        }
        catch(NullPointerException npe)
        {
            System.out.println(npe);
            System.out.println("File \"Members.dat\" is empty");
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mainPanel = new javax.swing.JPanel();
        MainMenu = new javax.swing.JPanel();
        RegNewMember = new javax.swing.JButton();
        ManageMembers = new javax.swing.JButton();
        ManageTeams = new javax.swing.JButton();
        ViewTourParticipants = new javax.swing.JButton();
        ManageEconomy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RegisterNewMember = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        Name1 = new javax.swing.JLabel();
        EmailAddressTF = new javax.swing.JTextField();
        Name2 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        Name4 = new javax.swing.JLabel();
        Name5 = new javax.swing.JLabel();
        Name6 = new javax.swing.JLabel();
        AddressTF = new javax.swing.JTextField();
        ZipCodeTF = new javax.swing.JTextField();
        PhoneNumberTF = new javax.swing.JTextField();
        DateOfBirthTF = new javax.swing.JTextField();
        CityTF = new javax.swing.JTextField();
        ConfirmChanges = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        MainMenu1 = new javax.swing.JButton();
        SaveMembers = new javax.swing.JButton();
        ManageMember = new javax.swing.JPanel();
        ManMembers = new javax.swing.JLabel();
        MainMenu2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MembersTable = new javax.swing.JTable();
        RegisterNewMember1 = new javax.swing.JButton();
        CancelMembership = new javax.swing.JButton();
        MemberInfo = new javax.swing.JButton();
        MemberInformation = new javax.swing.JPanel();
        ChosenMemberName = new javax.swing.JLabel();
        MainMenu3 = new javax.swing.JButton();
        ActivityStatus = new javax.swing.JLabel();
        MemberID = new javax.swing.JLabel();
        DateOfJoing = new javax.swing.JLabel();
        MemberType = new javax.swing.JLabel();
        ActivityStatusTFMI = new javax.swing.JTextField();
        MemberIDTFMI = new javax.swing.JTextField();
        MemberTypeMI = new javax.swing.JTextField();
        DateOfJoiningTFMI = new javax.swing.JTextField();
        DateOfJoing2 = new javax.swing.JLabel();
        ArrearsBalance = new javax.swing.JLabel();
        DateOfJoing4 = new javax.swing.JLabel();
        DateOfJoiningTFMI2 = new javax.swing.JTextField();
        DateOfJoiningTFMI3 = new javax.swing.JTextField();
        ArrearsBalanceTFMI = new javax.swing.JTextField();

        jMenuItem1.setText("View / change selected member info");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cancel membership");
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("Register membership");
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        RegNewMember.setText("Register new member");
        RegNewMember.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RegNewMemberActionPerformed(evt);
            }
        });

        ManageMembers.setText("Manage members");
        ManageMembers.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ManageMembersActionPerformed(evt);
            }
        });

        ManageTeams.setText("Manage Teams");

        ViewTourParticipants.setText("View tournament participants");

        ManageEconomy.setText("Manage economy");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Delfinen Svømmeklub");

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegNewMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageTeams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewTourParticipants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageEconomy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(RegNewMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageMembers)
                .addGap(30, 30, 30)
                .addComponent(ManageTeams)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewTourParticipants)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(ManageEconomy)
                .addGap(82, 82, 82))
        );

        mainPanel.add(MainMenu, "card2");

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setText("Name:");

        Name1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name1.setText("Email address: ");

        Name2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name2.setText("Address:");

        Name3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name3.setText("City:");

        Name4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name4.setText("Phone number:");

        Name5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name5.setText("Date of birth:");

        Name6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name6.setText("Zip code:");

        ConfirmChanges.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ConfirmChanges.setText("Confirm changes");
        ConfirmChanges.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConfirmChangesActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ResetActionPerformed(evt);
            }
        });

        MainMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MainMenu1.setText("Main menu");
        MainMenu1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MainMenu1ActionPerformed(evt);
            }
        });

        SaveMembers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SaveMembers.setText("Save members");

        javax.swing.GroupLayout RegisterNewMemberLayout = new javax.swing.GroupLayout(RegisterNewMember);
        RegisterNewMember.setLayout(RegisterNewMemberLayout);
        RegisterNewMemberLayout.setHorizontalGroup(
            RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                        .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SaveMembers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConfirmChanges, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Reset)
                        .addContainerGap(213, Short.MAX_VALUE))
                    .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                        .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name3)
                                    .addComponent(Name6)
                                    .addComponent(Name5)
                                    .addComponent(Name4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CityTF, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(ZipCodeTF)
                                    .addComponent(DateOfBirthTF)
                                    .addComponent(PhoneNumberTF)))
                            .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name1)
                                    .addComponent(Name)
                                    .addComponent(Name2))
                                .addGap(9, 9, 9)
                                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(EmailAddressTF)
                                    .addComponent(AddressTF))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MainMenu1))))
        );
        RegisterNewMemberLayout.setVerticalGroup(
            RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterNewMemberLayout.createSequentialGroup()
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterNewMemberLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(MainMenu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name1)
                    .addComponent(EmailAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name2)
                    .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name3)
                    .addComponent(CityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name6)
                    .addComponent(ZipCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name5)
                    .addComponent(DateOfBirthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name4)
                    .addComponent(PhoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(RegisterNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmChanges)
                    .addComponent(Reset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(SaveMembers)
                .addGap(25, 25, 25))
        );

        mainPanel.add(RegisterNewMember, "RegiNewMember");

        ManMembers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ManMembers.setText("Manage members");

        MainMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MainMenu2.setText("Main Menu");
        MainMenu2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MainMenu2ActionPerformed(evt);
            }
        });

        MembersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Name", "MID", "Status"
            }
        ));
        MembersTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                MembersTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(MembersTable);

        RegisterNewMember1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegisterNewMember1.setText("Register new member");
        RegisterNewMember1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RegisterNewMember1ActionPerformed(evt);
            }
        });

        CancelMembership.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelMembership.setText("Cancel membership");

        MemberInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MemberInfo.setText("View / chance member info");

        javax.swing.GroupLayout ManageMemberLayout = new javax.swing.GroupLayout(ManageMember);
        ManageMember.setLayout(ManageMemberLayout);
        ManageMemberLayout.setHorizontalGroup(
            ManageMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageMemberLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(ManMembers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(MainMenu2))
            .addGroup(ManageMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(ManageMemberLayout.createSequentialGroup()
                        .addComponent(RegisterNewMember1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelMembership))
                    .addComponent(MemberInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ManageMemberLayout.setVerticalGroup(
            ManageMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageMemberLayout.createSequentialGroup()
                .addGroup(ManageMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManMembers)
                    .addComponent(MainMenu2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(ManageMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterNewMember1)
                    .addComponent(CancelMembership))
                .addGap(27, 27, 27)
                .addComponent(MemberInfo)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        mainPanel.add(ManageMember, "MembersManage");

        ChosenMemberName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ChosenMemberName.setText("-----------------");

        MainMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MainMenu3.setText("Main menu");

        ActivityStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ActivityStatus.setText("Activity status:");

        MemberID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MemberID.setText("Member ID:");

        DateOfJoing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateOfJoing.setText("Date of joining:");

        MemberType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MemberType.setText("Member type:");

        ActivityStatusTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ActivityStatusTFMI.setText("jTextField1");

        MemberIDTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MemberIDTFMI.setText("jTextField1");

        MemberTypeMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MemberTypeMI.setText("jTextField1");

        DateOfJoiningTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DateOfJoiningTFMI.setText("jTextField1");

        DateOfJoing2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateOfJoing2.setText("Date of joining:");

        ArrearsBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ArrearsBalance.setText("Arrears balance:");

        DateOfJoing4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateOfJoing4.setText("Date of joining:");

        DateOfJoiningTFMI2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DateOfJoiningTFMI2.setText("jTextField1");

        DateOfJoiningTFMI3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DateOfJoiningTFMI3.setText("jTextField1");

        ArrearsBalanceTFMI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ArrearsBalanceTFMI.setText("jTextField1");

        javax.swing.GroupLayout MemberInformationLayout = new javax.swing.GroupLayout(MemberInformation);
        MemberInformation.setLayout(MemberInformationLayout);
        MemberInformationLayout.setHorizontalGroup(
            MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberInformationLayout.createSequentialGroup()
                .addComponent(ChosenMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(MainMenu3))
            .addGroup(MemberInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MemberInformationLayout.createSequentialGroup()
                            .addComponent(DateOfJoing)
                            .addGap(18, 18, 18)
                            .addComponent(DateOfJoiningTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MemberInformationLayout.createSequentialGroup()
                            .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ActivityStatus)
                                .addComponent(MemberType))
                            .addGap(18, 18, 18)
                            .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(MemberInformationLayout.createSequentialGroup()
                                    .addComponent(MemberTypeMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DateOfJoing4))
                                .addGroup(MemberInformationLayout.createSequentialGroup()
                                    .addComponent(MemberIDTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DateOfJoing2))
                                .addGroup(MemberInformationLayout.createSequentialGroup()
                                    .addComponent(ActivityStatusTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(ArrearsBalance)))))
                    .addComponent(MemberID))
                .addGap(18, 18, 18)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateOfJoiningTFMI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArrearsBalanceTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateOfJoiningTFMI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MemberInformationLayout.setVerticalGroup(
            MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberInformationLayout.createSequentialGroup()
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MainMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChosenMemberName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActivityStatus)
                    .addComponent(ActivityStatusTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArrearsBalance)
                    .addComponent(ArrearsBalanceTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MemberID)
                    .addComponent(MemberIDTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateOfJoing2)
                    .addComponent(DateOfJoiningTFMI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MemberType)
                    .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DateOfJoiningTFMI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MemberTypeMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DateOfJoing4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateOfJoing)
                    .addComponent(DateOfJoiningTFMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 257, Short.MAX_VALUE))
        );

        mainPanel.add(MemberInformation, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegNewMemberActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegNewMemberActionPerformed
    {//GEN-HEADEREND:event_RegNewMemberActionPerformed
        //card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "RegiNewMember");
    }//GEN-LAST:event_RegNewMemberActionPerformed

    private void ManageMembersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ManageMembersActionPerformed
    {//GEN-HEADEREND:event_ManageMembersActionPerformed
        //addRowToTable();
        card.show(mainPanel, "MembersManage");
    }//GEN-LAST:event_ManageMembersActionPerformed

    private void ConfirmChangesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConfirmChangesActionPerformed
    {//GEN-HEADEREND:event_ConfirmChangesActionPerformed
        try
        {
            // should be removed from this method at some point in time
            c.updateMemberList();
        }
        catch (Exception ex)
        {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int zipCode = Integer.parseInt(this.ZipCodeTF.getText());
        long phoneNumber = Long.parseLong(this.PhoneNumberTF.getText());
        String name = this.NameTF.getText();
        String address = this.AddressTF.getText();
        String city = this.CityTF.getText();
        String email = this.EmailAddressTF.getText();
        //LocalDate dateOfBirth = LocalDate.parse(this.DateOfBirthTF.getText()); //works if string is formatted like localdate (ex 2016-08-16)
        
        String dateOfBirthString = this.DateOfBirthTF.getText();
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("d/MM/yyyy");
        
        LocalDate dateOfBirth = LocalDate.parse(dateOfBirthString, dateFormat);
        
        validation();
        
        c.registerNewMember(zipCode, phoneNumber, name, address, city, email, dateOfBirth);
        System.out.print("MemberList size: " + c.getMemberList().size());
        
        try
        {
            // should be removed from this methid at some point in time
            c.saveMemberList();
        }
        catch (Exception ex)
        {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Object rowData[] = new Object[3];
                    
        rowData[0] = c.getLastAddedMember().getName();
        rowData[1] = c.getLastAddedMember().getMemberID();
        rowData[2] = c.getLastAddedMember().getActivityStatusString();
        model.addRow(rowData);
        reset();
    }//GEN-LAST:event_ConfirmChangesActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ResetActionPerformed
    {//GEN-HEADEREND:event_ResetActionPerformed
        reset();
    }//GEN-LAST:event_ResetActionPerformed

    private void MembersTableMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_MembersTableMouseReleased
    {//GEN-HEADEREND:event_MembersTableMouseReleased
         //Mouse Released is apperantly equal to mouse right click???? 
        if(evt.isPopupTrigger()) //If this event is triggrede (java.awt.event.Mouse event evt) - the parameter for this method
        {
            jPopupMenu1.show(this, evt.getX(), evt.getY()); //show the popup at memberstable at this event x,y cordinates
        }
    }//GEN-LAST:event_MembersTableMouseReleased

    private void MainMenu1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MainMenu1ActionPerformed
    {//GEN-HEADEREND:event_MainMenu1ActionPerformed
        mainMenu();
    }//GEN-LAST:event_MainMenu1ActionPerformed

    private void MainMenu2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MainMenu2ActionPerformed
    {//GEN-HEADEREND:event_MainMenu2ActionPerformed
        mainMenu();
    }//GEN-LAST:event_MainMenu2ActionPerformed

    private void RegisterNewMember1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegisterNewMember1ActionPerformed
    {//GEN-HEADEREND:event_RegisterNewMember1ActionPerformed
        card.show(mainPanel, "RegiNewMember");
    }//GEN-LAST:event_RegisterNewMember1ActionPerformed

    public void validation()
    {
        int zipCode = Integer.parseInt(this.ZipCodeTF.getText());
        long phoneNumber = Long.parseLong(this.PhoneNumberTF.getText());
        
        if(zipCode < 1000 || zipCode > 9999)
        {
            JOptionPane.showMessageDialog(null, "The field zip must contains excalty 4 digits", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        if(phoneNumber < 10000000 || phoneNumber > 99999999)
        {
            JOptionPane.showMessageDialog(null, "The field phone number must contains excalty 8 digits", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        if(this.NameTF.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "The field name cannot be empty", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        if(this.AddressTF.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "The field address cannot be empty", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        if(this.CityTF.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "The field city cannot be empty", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        if(this.EmailAddressTF.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "This email is not valid", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        if(this.DateOfBirthTF.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "The field date of birth can not be empty", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void reset()
    {
        this.ZipCodeTF.setText("");
        this.PhoneNumberTF.setText("");
        this.NameTF.setText("");
        this.AddressTF.setText("");
        this.CityTF.setText("");
        this.EmailAddressTF.setText("");
        this.DateOfBirthTF.setText("");
    }
    
    public void populateTable()
    {
        model = (DefaultTableModel) MembersTable.getModel();
        System.out.print("MemberList size is: " + c.getMemberList().size());
        
        Object rowData[] = new Object[3];
        
        for(int i = 0; i < c.getMemberlist().size(); ++i)
        {
            
            rowData[0] = c.getMemberlist().get(i).getName();
            rowData[1] = c.getMemberlist().get(i).getMemberID();
            rowData[2] = c.getMemberlist().get(i).getActivityStatusString();
            model.addRow(rowData);
            
        }  
    }
    
    public int rowSelected()
    {
        int index;
        
        if(MembersTable.getSelectionModel().isSelectionEmpty())
        {
            System.out.print("No rows selected");
        }
        
        index = MembersTable.getSelectedRow();
        return index;    
    }
    
    public void mainMenu()
    {
        card.first(mainPanel);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActivityStatus;
    private javax.swing.JTextField ActivityStatusTFMI;
    private javax.swing.JTextField AddressTF;
    private javax.swing.JLabel ArrearsBalance;
    private javax.swing.JTextField ArrearsBalanceTFMI;
    private javax.swing.JButton CancelMembership;
    private javax.swing.JLabel ChosenMemberName;
    private javax.swing.JTextField CityTF;
    private javax.swing.JButton ConfirmChanges;
    private javax.swing.JTextField DateOfBirthTF;
    private javax.swing.JLabel DateOfJoing;
    private javax.swing.JLabel DateOfJoing2;
    private javax.swing.JLabel DateOfJoing4;
    private javax.swing.JTextField DateOfJoiningTFMI;
    private javax.swing.JTextField DateOfJoiningTFMI2;
    private javax.swing.JTextField DateOfJoiningTFMI3;
    private javax.swing.JTextField EmailAddressTF;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton MainMenu1;
    private javax.swing.JButton MainMenu2;
    private javax.swing.JButton MainMenu3;
    private javax.swing.JLabel ManMembers;
    private javax.swing.JButton ManageEconomy;
    private javax.swing.JPanel ManageMember;
    private javax.swing.JButton ManageMembers;
    private javax.swing.JButton ManageTeams;
    private javax.swing.JLabel MemberID;
    private javax.swing.JTextField MemberIDTFMI;
    private javax.swing.JButton MemberInfo;
    private javax.swing.JPanel MemberInformation;
    private javax.swing.JLabel MemberType;
    private javax.swing.JTextField MemberTypeMI;
    private javax.swing.JTable MembersTable;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Name4;
    private javax.swing.JLabel Name5;
    private javax.swing.JLabel Name6;
    private javax.swing.JTextField NameTF;
    private javax.swing.JTextField PhoneNumberTF;
    private javax.swing.JButton RegNewMember;
    private javax.swing.JPanel RegisterNewMember;
    private javax.swing.JButton RegisterNewMember1;
    private javax.swing.JButton Reset;
    private javax.swing.JButton SaveMembers;
    private javax.swing.JButton ViewTourParticipants;
    private javax.swing.JTextField ZipCodeTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
